---
# == Re-useable Definitions ==================================================

# Default service definition for all (incl. postgres/redis/...)
x-service-default: &service_default
  env_file:
    - .env
  networks:
    - internal_net
    - external_net
  restart: unless-stopped


# == Services ===============================================================

services:

  # -- PostgreSQL Server -----------------------------------------------------
  #
  # We use the default configuration, but mount a volume for the data for
  # persistent storage.

  postgres:
    <<: *service_default
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    secrets:
      - db-password
    volumes:
      - type: bind
        source: ${volumes_basedir:-./volumes}/postgres/data
        target: /var/lib/postgresql/data

  # -- redis -----------------------------------------------------------------
  #
  # We use the default configuration, but mount a volume for the data for
  # persistent storage.

  redis:
    <<: *service_default
    image: redis:alpine
    container_name: redis
    hostname: redis
    volumes:
      - type: bind
        source: ${volumes_basedir:-./volumes}/redis/data
        target: /data

  # -- pgAdmin ----------------------------------------------------------------
  #
  # Useful for interactive database administration.

  pgadmin:
    <<: *service_default
    image: dpage/pgadmin4:8.3
    container_name: pgadmin
    hostname: pgadmin
    secrets:
      - db-password
      - pgadmin-password
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ${volumes_basedir:-./volumes}/pgadmin/data
        target: /private/var/lib/pgadmin
      - type: bind
        source: ${config_basedir:-./config}/pgadmin/servers.json
        target: /pgadmin4/servers.json


# == Secrets ================================================================

secrets:
  # The PostgreSQL database password.
  db-password:
    file: ${secrets_basedir:-./secrets}/db-password
  # The pgAdmin admin password.
  pgadmin-password:
    file: ${secrets_basedir:-./secrets}/pgadmin-password


# == Networks ===============================================================

networks:
  internal_net:
    driver: bridge
    internal: true
  external_net:
    driver: bridge

