---

# == Re-useable Definitions ==================================================

# Default service definition for all (incl. postgres/redis/...)
x-service-default: &service_default
  env_file:
    - .env
  networks:
    - internal_net
    - external_net
  restart: unless-stopped


# == Services ===============================================================

services:

  # == Core Services =======================================================

  # -- PostgreSQL Server -----------------------------------------------------
  #
  # We use the default configuration, but mount a volume for the data for
  # persistent storage.

  postgres:
    <<: *service_default
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    secrets:
      - db-password
    volumes:
      - type: bind
        source: ${volumes_basedir:-./volumes}/postgres/data
        target: /var/lib/postgresql/data

  # -- Redis -----------------------------------------------------------------
  #
  # We use the default configuration, but mount a volume for the data for
  # persistent storage.

  redis:
    <<: *service_default
    image: redis:alpine
    container_name: redis
    hostname: redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: ${volumes_basedir:-./volumes}/redis/data
        target: /data
      - type: bind
        source: ${config_basedir:-./config}/redis/redis.conf
        target: /etc/redis/redis.conf

  # == Monitoring Services ===================================================

  # -- pgAdmin ----------------------------------------------------------------
  #
  # Useful for interactive database administration.

  pgadmin:
    <<: *service_default
    image: dpage/pgadmin4:8.3
    container_name: pgadmin
    hostname: pgadmin
    secrets:
      - db-password
      - pgadmin-password
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ${volumes_basedir:-./volumes}/pgadmin/data
        target: /private/var/lib/pgadmin
      - type: bind
        source: ${config_basedir:-./config}/pgadmin/servers.json
        target: /pgadmin4/servers.json

  # -- Redis Commander --------------------------------------------------------
  #
  # A web UI for Redis.

  redis-commander:
    <<: *service_default
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    hostname: redis-commander
    depends_on:
      - redis
    secrets:
      - redis-password
      - redis-commander-password
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD_FILE: /run/secrets/redis-password
      REDIS_DB: 0
      # UI Authentication
      HTTP_USER: admin
      HTTP_PASSWORD_FILE: /run/secrets/redis-commander-password


# == Secrets ================================================================

secrets:
  # The PostgreSQL database password.
  db-password:
    file: ${secrets_basedir:-./secrets}/db-password
  # The pgAdmin admin password.
  pgadmin-password:
    file: ${secrets_basedir:-./secrets}/pgadmin-password
  # The Redis password.
  redis-password:
    file: ${secrets_basedir:-./secrets}/redis-password
  # The Redis Commander UI password.
  redis-commander-password:
    file: ${secrets_basedir:-./secrets}/redis-commander-password

# == Networks ===============================================================

networks:
  internal_net:
    driver: bridge
    internal: true
  external_net:
    driver: bridge
