---

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shellcheck and yamllint
        run: sudo apt-get install -y shellcheck yamllint

      - name: Run linting via make
        run: make lint
